### ISSUE TITLE
write access violation. p was nullptr.

### ISSUE THREAD

**Issue by jamieS95** [spectre1989/odin#1]
![githubs](https://user-images.githubusercontent.com/50465426/94013003-638d7b80-fda1-11ea-8460-e339ec9703f8.png)

**Comment by spectre1989** [comment]
Interesting, no chosen physical device - maybe step through the code which chooses the physical device and see if you can figure out why it's failing

**Comment by jamieS95** [comment]
i think i found the issue, the code presumes we have a graphics card, VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
but changing it to  VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU fixes the assert

**Comment by spectre1989** [comment]
ah ha, yeah that makes sense - this graphics code is very bare bones. What I should do is have it try with a discrete gpu first and then fall back to integrated if it can't find anything else.

**Comment by jamieS95** [comment]
got everything working except how to compile a server, client is working.
Thanks for your articles and providing source code :)
